// Muestras parciales extraídas del manuscrito facilitado para la web de Jorge Schwember F.
// Cada texto está cortado antes del desenlace para preservar la lectura completa del libro.
window.storyPreviews = [
  {
    id: "enigma-lucrecia",
    title: "El (la) enigma de Lucrecia",
    meta: "Relato · Herencia y desquite",
    dek: "Una celebración familiar, una fortuna inmensa y una anfitriona que parece haber diseñado cada detalle de su revancha.",
    book: "Veinte relatos de sátira y una obra de teatro no desesperada",
    amazonUrl:
      "https://www.amazon.com/Veinte-relatos-s%C3%A1tira-teatro-desesperada-ebook/dp/B0FPBJP8Z6",
    publisherUrl:
      "https://nuevacarpetaediciones.cl/producto/veinte-relatos-de-satira-y-una-obra-de-teatro-no-desesperada/",
    paragraphs: [
      "Lucrecia Tellez contrató los servicios de una productora de eventos para celebrar su octogésimo cumpleaños. El lugar elegido fue la Hacienda Juntas en la comuna de Monte Patria. Casona patronal de estilo colonial con 200 años de existencia emplazada en un parque de cuatro hectáreas con tres mil metros construidos. Sus veinticinco habitaciones fueron copadas por el extenso familión et additus de Lucrecia. Todos ubicados por grupos familiares afines con opción de trueque de las ubicaciones, hubo varios de estos, lo cual era de esperar en un grupo de setenta personas. Años antes a muchos de ellos les había entregado un cuantioso donativo que pocos agradecieron. Y de cierta manera se podía considerar como un presagio del legado de su inmensa fortuna a repartir. La conmemoración de la octogenaria mujer, renuente en un comienzo por la escasa afinidad con sus huéspedes, le brindó la oportunidad de su contundente desquite. Ella no podía olvidar el intento de la declaración de interdicción frustra por sus más cercanos que contaron con la confabulación de su cura confesor.",
      "Su amiga notario pudo detener a tiempo tan execrable acción. Tampoco eran menores las transgresiones a su privacidad. El sistema de seguridad de su finca de Freirina tenía tres perímetros de protección, al mes fue vulnerado. Prescindió del instalador original, su sobrino nieto Alvaro, para hacer los ajustes correspondientes. La empresa externa contratada para la investigación le confirmó la sospecha que dado lo complejo del sistema, el diseñador inicial habría tenido alguna participación en la violación electrónica. Al menos esta maquinación le sirvió para interiorizarse del funcionamiento de cámaras de seguridad, detectores de movimiento, ruidos, humo y monóxido de carbono. Este conocimiento sería de mucha utilidad para su planificada estratagema. Pero el evento mayor fue el intento de asesinarla siendo colisionado su auto en la carretera Freirina Vallenar por una gran camioneta que resultó ser robada. La destreza de su chofer custodio Romualdo y el Mercedes Benz blindado la salvaron. Responsables no se encontraron. Estos atentados la obligaron a llevar una vida de claustro; ni siquiera podía visitar el hogar de ancianos creado por la Fundación junto a su marido.",
      "En dos ocasiones requirió tratamientos médicos en la capital debiendo arrendar un helicóptero privado para su desplazamiento. El festejo comenzó un día viernes por la tarde y el término se programó para el domingo a mediodía. Unos pocos invitados le ofrecieron el pago de su alícuota desdeñándolos a todos. Para ella el gasto era una bicoca no resarciéndola del placer por la venganza que tendría. Lucrecia concurrió al evento con su dama de compañía, Cecilia, dejando al resto de su séquito de servidumbre en su finca de Freirina. Se trasladaron en el Porsche 911 GT3 y ocupó junto a su acompañante la suite presidencial; otro resguardo para evitar divulgación de información sensible a terceros. A su chofer le había otorgado vacaciones obligadas desde hacía una semana ubicándolo en la ciudad puerto de Coquimbo; esto formaba parte de la coartada. Lucrecia Tellez nació en Tulahuén en 1944 (la toponimia no es lo que puedan elucubrar, es lugar de garzas), octava hija de un pirquinero, Demetrio, y una lavandera analfabeta, María.",
      "Contaba con un año de edad cuando se mudaron a Monte Patria. Su abuelo paterno Engelberto, obrero, trabajaba desde los inicios en la construcción de la central hidroeléctrica Los Molles en el río del mismo nombre, afluente del Limarí. Este hombre sencillo fue señero en el desarrollo familiar de su grupo cercano y afines. Ejemplo de responsabilidad, laboriosidad y respeto, dejó una impronta para quienes tuvieron la suerte de convivir con él. Nunca hizo aspaviento de su membresía comunista. Esta afiliación política le serviría a la familia en los años venideros con la asunción de Allende a la presidencia del paisillo corrupto. No escatimaba ocasión para llevar a su hijo favorito al lugar de trabajo; en aquella época se estaba realizando los estudios topográficos y la hidrología de la zona. Así Demetrio comenzó a conocer la Pachamama para luego aprender a leerla y descifrar sus códices. Los acrecentó cuando fue peón en la construcción del embalse La Paloma. Después se dedicó a faenas mineras obteniendo la inscripción de un modesto trapiche.",
      "En el interín, la niña comenzó su educación en la escuela pública del poblado. Hasta que un día la rueda de la fortuna se detuvo y el modesto minero supo subirse a ella encontrando la mina de oro subterránea más grande cerca de la desembocadura del Limarí, activa hasta ahora, Talcuna. Sabedores de la importancia de la educación, enviaron a la generación de estudiantes a La Serena; en ese momento en su apogeo por el desarrollo impulsado por el presidente González Videla. Los varones fueron enviados al internado del Colegio Salesiano y las mujeres al internado del Colegio de La Providencia, donde el abuelo paterno de este relator diseñó la capilla, monumento nacional en deterioradas condiciones. Esta tercera generación tuvo buen desempeño estudiantil, la mayoría prosiguió estudios universitarios en el área financiera y administrativa ocupando sus conocimientos en la próspera propiedad minera. La joven Lucrecia también trabajaba en ella durante las vacaciones de verano; y fue así como conoció a Antonio Fagalde estudiante egresado de ingeniería civil que hacía su práctica en las faenas mineras.",
      "Cupido la flechó, cautivándole su acento español, su estampa y sus modales refinados, quedando fascinada con la enseñanza impartida en la caza de conejos y liebres con escopeta. El matrimonio se consagró al año siguiente. Pero la desventura también les tocó con el nacimiento de un niño prematuro de ocho meses con sufrimiento fetal y secuelas neuromotoras considerables, cambiándoles su hado. Ella quedó estéril, histerectomía por placenta acreta. Gran parte de su quehacer lo volcó en su minusválido hijo quien murió a los cincuenta años de edad sobreviviendo a su padre; en otro entorno socioeconómico habría muerto antes del año de vida (¿han observado que en nuestro medio se ocupa fallecido?). Llegaron a tenerle una alberca temperada de considerables dimensiones además de una inmensa cohorte de asistentes. El vasco era una máquina pensante en los negocios, introdujo tecnología de vanguardia en la mina superando los rendimientos esperados. A pesar del gran aporte de Antonio, su suegro fue renuente a incorporarlo en la sociedad; la experiencia con sus otros yernos le hacía ser cauto.",
      "La única amenaza real fue la casi confiscación de sus faenas mineras durante el gobierno de la Unidad Popular, salvándole la condición política del abuelo Engelberto y algunas cooperaciones económicas a la causa o, mejor dicho, a sus personeros. El español fue marginándose paulatinamente del amparo de su suegro para iniciar una empresa de transportes. Había detectado que los productos agrícolas del Limarí como papas, apio, zapallo, aceitunas, cítricos, entre otros, abastecían en gran medida al terminal Lo Valledor en Santiago. Su esposa fue de gran ayuda en la administración del negocio para después con la introducción de la computación ser un baluarte en las numerosas empresas que formaron. Y ella lo hacía todo desde la casa sin desatender a su dependiente vástago quedándole tiempo para su nueva distracción, cetrería con aves regionales más el tiro al plato. Antonio con este ente contralor liberó su energía empresarial creando una constructora e inmobiliaria adjudicándose la edificación de los resorts Puerto Velero, Playa Blanca y Marbella.",
      "Sus infatigables afanes eran descomunales, este Midas ibérico luego formó invernaderos para tomates, viñedos, cultivo de ostras y ostiones. Nunca se supo el motivo de su marginación de la actividad minera, incluso vendiendo la participación de Lucrecia a Barrick a la muerte de su suegro por silicosis. El único negocio trunco fue una constructora de caminos por ser renuente a los sobornos a los funcionarios públicos del área. Su infalible habilidad comercial lo posicionó como un destacado asesor económico cobrando aranceles superiores en tres veces a los del mercado. El resguardo de su riqueza lo fue acrecentando exponencialmente en las Islas Vírgenes como cliente VIP. Sus infrecuentes vacaciones eran en Saint Thomas donde llegaron a sociabilizar con los altos directivos del banco. A la muerte de Antonio, Lucrecia contaba con una fortuna de más de setenta millones de dólares en efectivo. El agasajo comenzó a las 20:00 horas en el salón de eventos decorado para la ocasión. Las cortinas del estrado se abrieron para dar inicio con un deslumbrante despliegue de efectos audiovisuales.",
      "Luego hizo su aparición en el escenario la presentadora de televisión Monserrat Aguirre con la rutinaria perorata, a continuación, la invitación al bar abierto y el anuncio de una rifa para 24 de los asistentes quienes tendrían la opción de compartir la mesa con la anfitriona en turnos de seis durante las dos cenas del encuentro; nadie renunció a este privilegio dado el presagio de retribución a los afortunados. Las ocho mesas redondas finamente dispuestas para ocho comensales fueron servidas por una comparsa de garzones con botines negros relucientes, pantalones blancos, jubón carmesí y librea negra. El maitre atendió en todo momento a Lucrecia; sus viandas venían discretamente desde la cocina. El bar abierto consideraba sólo alcoholes de la zona: pajarete de Vallenar, pisco de Alto del Carmen, vino y espumante del Elqui, cerveza artesanal de Peralillo (lugar donde se fabrica el mejor ají licuado del mundo: Diaguitas). El pescado y los mariscos provistos desde Tongoy.",
      "Los entremeses (¿no debería ser entremesas?) lo componían camarones gratinados del Limarí, chochas apanadas, ostras, pastel de jaiba, ostiones al pilpil, empanaditas de loco-queso de cabra, fondos de alcachofas con aceitunas de Huasco, canapés de Luz Charme de Viña del Mar llevados por Frigo Cargo; Lucrecia fue enfática en no ocupar la empresa Chilexpress que en más de una ocasión no respondió por sus encomiendas. Un mago ambulante distraía el engullimiento frenético de las exquisiteces. Una vez saciada la apetencia, la presentadora anunció la intervención de Bombo Fica a quien Lucrecia le solicitó al momento de la firma del contrato, un libreto que abordara la parentela del mundo chileno. Muchos de los tópicos tratados por el comediante era una descarnada e irónica crítica a este grupo social. La mayoría de ellos no se identificaron con las premisas del humorista; las delicias de los platos en las mesas fueron un evasivo antídoto.",
      "Terminada la presentación de Fica, se procedió al cambio de turno de los premiados en la mesa de tía Luque, cada uno se retiraba con un sobre previamente escondido bajo del cojín de la silla con un suculento efectivo.",
    ],
  },
  {
    id: "tia-olga-penurias",
    title: "Mi tía Olga y sus penurias",
    meta: "Relato · Sátira e intimidad",
    dek: "Un dispositivo imposible abre la memoria privada de una tía formidable y transforma la protección familiar en invasión, culpa y morbo.",
    book: "Veinte relatos de sátira y una obra de teatro no desesperada",
    amazonUrl:
      "https://www.amazon.com/Veinte-relatos-s%C3%A1tira-teatro-desesperada-ebook/dp/B0FPBJP8Z6",
    publisherUrl:
      "https://nuevacarpetaediciones.cl/producto/veinte-relatos-de-satira-y-una-obra-de-teatro-no-desesperada/",
    paragraphs: [
      "Le implanté el Ceteceri (por sus siglas en inglés, cerebral telepathic reader inducer) detrás de su oreja izquierda a las pocas semanas de enviudar. La engañé comentándole que su audición mejoraría en todo sentido y podría seguir disfrutando de Mahler; bastó mencionarle a su compositor favorito para que mordiera la carnada. Tuve varios motivos para hacerlo, el principal e inicial fue brindarle protección; sabía que seguiría aferrada a su soledad, si bien a sus ochenta y tres años y sin maternidad, era del todo autovalente. Con todo, los años pasan y en algún momento requeriría cuidados propios de la edad y aunque residimos cerca no tenía en mis planes acogerla. En algunos aspectos nos parecemos, como vivir solos. La información obtenida por el adminículo fue entregándome antecedentes insospechados de su biografía que fueron polarizando morbosamente mis intenciones y que relataré más adelante. El Ceteceri es el fruto de mi investigación durante varias décadas apoyada por conocimientos empíricos que tengo sobre electrónica, informática y programación.",
      "Eso, agregado a mi curiosidad intrínseca, me valió el apodo de las pocas personas que me estiman, de Giro sin Tornillos. Hasta hace unos años la dificultad que tenía, era el gran volumen del aparato; pero la nanotecnología me permitió crear un dispositivo del tamaño de una lenteja y baterías de larga duración con una vida útil de cinco años. El primer prototipo se lo coloqué a mi perra Dominga Antonia; al no tener traductor del lenguaje perruno mis interpretaciones de las señales fueron frustras. Si pude observar cambios en su comportamiento: tenía pesadillas al dormir con ladridos estridentes, sus delicados modales de urbanidad se transformaban en grotescos gestos y su obediencia irrestricta pasó a rebeldía. Una noche manipulando el control remoto e intentando interpretar sus sueños, le sobrevino un paro cardiaco que no pude recuperar; solo atiné a desenergizar los elementos. Este fracaso me desmoralizó durante mucho tiempo y aunque no tenía la certeza, sentí que la asesiné; la muerte de mi perra, única compañera, estuvo cerca de cercenar mi invento.",
      "No obstante, los desprecios y humillaciones (ahora le llaman bullying, olvidando la riqueza del castellano) infringidos durante mis primeros años fueron superiores a mi desencanto, reconociendo que en mí prevalece el sentido de venganza. No puedo olvidar el taxativo comentario de los compañeros: Si a éste lo jodió la meningitis, y obscenidades que prefiero no recordar. Aún resuena el alias que me dieron: Trapo Sucio, reconozco algunas impudicias en mi quehacer, pero son muestras de la misantropía que me embarga desde esa época. Este óbito me desanimó durante meses, pero mis sentimientos de vendetta afloraron otra vez y con mayor resolución, retomando el desafío con más bríos. Quería demostrar que el muchacho que reparaba relojes, radios a pilas o cualquier equipo electrónico por valores puestos por los clientes, cuando pagaban, era capaz de algo único y trascendente.",
      "Compré un precioso joven conejo angora, era tal su beldad que tuve serias dudas en utilizarlo como animal de experimentación, más aún cuando el criadero me exigió una declaración ante el Ministerio de Animales, Tenencia Explícita y Huertos, El Matehue, que sería tratado como mascota de compañía. Decidí implantarle un Ceteceri de segunda generación o como dicen ahora un C 2.0 debajo de la glabela. Todo andaba bien, obedecía órdenes sencillas, acataba su nombre, Plutarco; incluso logré programar su horario de evacuación intestinal asignándole un lugar especial dentro de la casa. Tampoco pude interpretar las ondas del lenguaje conejuno. Las dificultades comenzaron en su pubertad, ya que desarrolló una compulsión masturbatoria irrefrenable, incluso con las zanahorias. Hastiado y quizás envidioso de tan libidinal conducta le fui permitiendo salir al patio a liberar tensiones. Una tarde durante mi acostumbrada siesta fui sobresaltado por el bip de emergencia que alertaba que el C 2.0 estaba llegando al límite de la distancia de comunicación.",
      "Cual bombero me levanté llamándolo con cariño, Plutarco no estaba dentro de la casa ni en el patio y la señal se iba atenuando hasta desaparecer. Le perdí el rastro en el bosque y espero que no haya ido con intención de quemarlo como fue la conjetura de un ministro de estado en la causa de los incendios forestales. Algo que aprendí con el gazapo fue que mi invento tenía cobertura de hasta un kilómetro. Desalentado con tantos infortunios –yo mismo– decidí colocarme un C 3.0 en la sien derecha previa explicación escrita de mi osadía, revisada por mi amigo abogado Claus Trincado Marambio, conocido en su círculo íntimo con la sigla CTM, así liberaba a terceros de toda responsabilidad, en especial a Jennifer, mi fiel asesora de hogar a tiempo parcial. En un comienzo no observé ningún cambio y debía ser así, ya que el sistema lo mantuve en reposo (stand-by).",
      "Cuando lo activé, previa verificación de los elementos (ahora le dicen check list), comencé de inmediato a presentar fasciculaciones musculares en las extremidades, aumento de la frecuencia cardíaca, distensión abdominal con sus respectivas consecuencias; cierto entorpecimiento en mis pensamientos y, unos deseos irrefrenables de lavar ropa: obsesión y obligación maternas. Estas cesaban al desconectar el sistema. Entonces me dediqué durante varios meses a calibrar el artilugio, lo más difícil de bloquear fue la inhibición de las notorias erecciones que presentaba espontáneamente al ver féminas voluptuosas y provocadoras. Después de muchos ensayo-error, logré manejar el artefacto. Para confirmarlo persuadí a Jennifer que lo comandara detallándole una pauta por seguir y grabar los acontecimientos. Lo hicimos durante dos semanas y tuve la cautela que ella no se apropiara de ningún antecedente. Le advertí expresamente que si había algún acoso sexual de mi parte bastaba con colocar el programa en off; discurro que lo hizo así: hay una opción de borrar memoria.",
      "Una vez evaluado mi comportamiento no tuve ninguna duda que había obtenido el Ceteceri 3.0 Plus, denominado así, pues además de inducir órdenes podía interferir con el pensamiento y fue el primero de cuatro, cada vez más perfeccionados que ocupé con mi tía Olga, empleando siempre el pretexto de su mejora auditiva. Ahora puedo relatarles mis vivencias con ella desde la información obtenida del dispositivo. Quise primero saber de su lejana niñez.",
    ],
  },
];
